# syntax=docker/dockerfile:1
ARG PYTHON_VERSION=3.13
FROM plone/server-builder:uv-${PYTHON_VERSION} AS builder

COPY . /src
WORKDIR /src

# Install package
RUN --mount=type=cache,target=/root/.cache \
    # --mount=type=bind,source=uv.lock,target=uv.lock \
    # --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    --mount=type=bind,source=mx.ini,target=mx.ini \
    uv tool run mxdev[uv] -c mx.ini && \
    uv sync \
        --no-dev \
        --no-group test \
        --group container \
        --no-editable

# Move skeleton files to /app
RUN <<EOT
    mv /app_skeleton/* /app
    rm -Rf /app_skeleton
    chmod +x /app/docker-entrypoint.sh
    mv scripts/create_site.py /app/scripts/create_site.py
EOT

# Compile translation files
RUN <<EOT
    /app/bin/python /compile_mo.py
EOT

FROM plone/server-acceptance:uv-${PYTHON_VERSION}

LABEL maintainer="Plone Community <collective@plone.org>" \
      org.label-schema.name="mastering-plone-project-acceptance" \
      org.label-schema.description="Ploneconf Site backend acceptance image." \
      org.label-schema.vendor="Plone Community"

ENV CONFIGURE_PACKAGES="plone.restapi,plone.volto,plone.volto.cors,ploneconf.site"
ENV APPLY_PROFILES="ploneconf.site:default"

# Copy /app from builder
COPY --from=builder /app /app

RUN <<EOT
    ln -s /data /app/var
EOT
